### PR TITLE
Updated username validation to match oVirt 4.5

### PR DESCRIPTION
**Pull request by janosdebugs**
## Please describe the change you are making

This change updates the username validation to match the 4.5 schema.

## Are you the owner of the code you are sending in, or do you have permission of the owner?

Yes

## The code will be published under the BSD 3 clause license. Have you read and understood this license?

Yes

### CODE REVIEW

**Comment by michalskrivanek** [comment]
lgtm, but i don't know if those assumptions are always ok now.
i.e. "@" may be a valid part of username now. @arso ?

**Comment by arso** [comment]
> lgtm, but i don't know if those assumptions are always ok now. i.e. "@" may be a valid part of username now. @arso ?

Yes - @ is a valid part of username and it has been such earlier. Ie. we could have  user identified by emails with LDAP integration. That was hidden in ovirt login screen but required for api calls.  I think there was/is an option to append a profile name (@internal  / @internalsso / @anyothercustomprofilename ) automatically ( a feature in 'extensions' configuration). 
@mwperina has recently told be about that. 
Anyway  '@'  is the first class citizen for ovirt user names

**Comment by janosdebugs** [comment]
@arso what's a good validation for usernames then? Is the scope always required? We wanted to catch users forgetting to enter the scope.

**Comment by michalskrivanek** [comment]
"at least one @" sound like a good validation

**Review by eslutsky — APPROVED** [review]

**Pull request merged**
