### PR TITLE
Refactoring the test helper

### PR DESCRIPTION
**Pull request by janosdebugs**
## Please describe the change you are making

This change refactors the test helper to make calling it more flexible. It also adds a second storage domain for testing.

## Are you the owner of the code you are sending in, or do you have permission of the owner?

yes

## The code will be published under the BSD 3 clause license. Have you read and understood this license?

yes

### CODE REVIEW

**Comment by janosdebugs** [comment]
FYI @eslutsky this change contains the secondary storage domain ID.

**Review by eslutsky — CHANGES_REQUESTED** [review]
please add a second SD  to the mock, so we can test this. and use it in case we copy disks between SDs.

**Review by thecreed — CHANGES_REQUESTED** [review]
can you add secondary storage domain to the mockClient  here https://github.com/oVirt/go-ovirt-client/blob/57035d4d1c124f65912ad91f597db83593119560/newmock.go#L29 ?

**Comment by janosdebugs** [comment]
> can you add secondary storage domain to the mockClient here
> 
> https://github.com/oVirt/go-ovirt-client/blob/57035d4d1c124f65912ad91f597db83593119560/newmock.go#L29
> 
> ?

It's already in this PR. Please take a look at the changes.

**Review by eslutsky — APPROVED** [review]

**Pull request merged**
