### PR TITLE
Fixes #2: constant overflows uint on 32 bit platforms

### LINKED ISSUE #2: Constant overflows uint on 32 bit platforms
## Describe the bug

When building on 32 bit platforms here is an error message appears:

```
newmock.go:43:3: constant 10737418240 overflows uint
```

## Expected behavior

Since the storage is provided in bytes all storage-related numbers should be provided in `uint64` and not `uint`.

### PR DESCRIPTION
**Pull request by janosdebugs**
## Please describe the change you are making

This change fixes #2 where an uint overflows on 32 bit platforms.

## Are you the owner of the code you are sending in, or do you have permission of the owner?

Yes

## The code will be published under the BSD 3 clause license. Have you read and understood this license?

Yes

### CODE REVIEW

**Comment by janosdebugs** [comment]
@Gal-Zaidman can I trouble you for a review?

**Comment by Gal-Zaidman** [comment]
/lgtm

> @Gal-Zaidman can I trouble you for a review?

Please also add it to:
- https://github.com/oVirt/go-ovirt-client/blob/main/client_vm.go#L20
- https://github.com/oVirt/go-ovirt-client/blob/main/client_vm.go#L39
- https://github.com/oVirt/go-ovirt-client/blob/main/client_vm/test_helper.go#L26

Started it on my PR[1] but this PR looks like the correct place :)

[1] https://github.com/oVirt/go-ovirt-client/pull/1/files#diff-c9e88235f1f664443d76481488dac388b8a048485d63e1c41d244add41d5940aR20

**Comment by janosdebugs** [comment]
@Gal-Zaidman are we ever going to have more than 4 billion CPUs/sockets/threads? That seems to be a bit of an overkill...

**Comment by janosdebugs** [comment]
@Gal-Zaidman let's not try and make this library dance to the oVirt clients tune, it's supposed to be the other way around.

**Comment by Gal-Zaidman** [comment]
> @Gal-Zaidman let's not try and make this library dance to the oVirt clients tune, it's supposed to be the other way around.

Does this change have any real effect?
I think it just makes the code a little bit easier to read, I can go either way here, but I'm just curious if there is some effect for using uint64 instead of unit?

**Comment by janosdebugs** [comment]
@Gal-Zaidman yes it does. `uint` is always the maximum integer for the given processor architecture. On 32 bit architectures `uint` is a 32 bit integer, while on 64 bit architectures `uint` is a 64 bit integer. If we write `uint64` that will cause a performance penalty on 32 bit systems. (Think: ARMv7, etc) See [StackOverflow](https://stackoverflow.com/questions/16427416/what-are-the-advantages-of-the-general-types-int-uint-over-specific-types-i)

**Review by Gal-Zaidman — APPROVED** [review]
code looks good to me, Approved

**Pull request merged**
