### PR TITLE
Fix 183 add ProxyFromEnvironment

### PR DESCRIPTION
**Pull request by evelynmitchell**
I haven't tested this, the issue explains the testing env needs a proxy which is either there (to test the fix) or not there (to verify the fix).

## Please describe the change you are making
Fix for Issue 183, add the ProxyFromEnvironment to the http.Client initialize.
...

## Are you the owner of the code you are sending in, or do you have permission of the owner?

Not owner. Will sign commit agreement.
.
## The code will be published under the BSD 3 clause license. Have you read and understood this license?

Yes.
...

### CODE REVIEW

**Comment by stbenjam** [comment]
I think unfortunately getting the proxy to work is going to be a multiple step effort.

It looks like go-ovirt, which go-ovirt-client vendors and uses, needs the connection builder fixed: 
   https://github.com/stbenjam/go-ovirt/blob/master/connection.go#L568-L576

But this code is generated by ovirt-engine-sdk-go:
https://github.com/oVirt/ovirt-engine-sdk-go/blob/8a2fc25bdf98903d7d5c0c2ce79d6113e7b12430/sdk/ovirtsdk/connection.go#L568-L578

So I think that's the first place to start. All of these need updating :-\

**Comment by janosdebugs** [comment]
Thank you for your input @stbenjam. As noted in the related issue, we will take a look next week. We will definitely need a test for this change, but patching go-ovirt is within our capabilities.

**Comment by janosdebugs** [comment]
@stbenjam @evelynmitchell in order to properly test using a proxy we have taken a bit more complex route in #185, so I'm closing this PR.

**Comment by evelynmitchell** [comment]
Thank you. This is what I hoped for, and a significant quality improvement.

**Pull request closed without merging**
